[phases.setup]
nixPkgs = ["dotnet-sdk_8"]

[phases.build]
cmds = [
  "dotnet restore application/backend/StockFlow.sln",
  "dotnet publish application/backend/src/StockFlow.API/StockFlow.API.csproj -c Release -o out"
]

[phases.start]
cmd = "dotnet out/StockFlow.API.dll"

[variables]
ASPNETCORE_ENVIRONMENT = "Production"
